##1. Amazon S3 — the foundation of AWS data lakes

##•	Create an S3 bucket and upload three CSV files representing raw claims from different partners.

# Creating an S3 Bucket
aws s3 mb s3://healthcare-datalake

# Uploading the partner A file
aws s3 cp claims_partner_a.csv \
s3://healthcare-datalake/raw/claims/2024-01-15/

# Uploading the partner B file
aws s3 cp claims_partner_b.csv \
s3://healthcare-datalake/raw/claims/2024-01-15/

# Uploading the partner C file
aws s3 cp claims_partner_c.csv \
s3://healthcare-datalake/raw/claims/2024-01-15/

---

##•	List all objects under the raw/claims/ prefix using both the AWS CLI and boto3.

--Using CLI

aws s3 ls \
s3://healthcare-datalake/raw/claims/ \
--recursive

--Using boto3

import boto3
s3 = boto3.client("s3")

response = s3.list_objects_v2(
    Bucket="healthcare-datalake",
    Prefix="raw/claims/"
)
for obj in response["Contents"]:
    print(obj["Key"])
    
--
##•	Write a Python function that checks whether a specific file exists in S3 before proceeding.
import boto3
s3 = boto3.client("s3")

def file_exists(bucket_name, file_key):
    try:
        s3.head_object(
            Bucket=bucket_name,
            Key=file_key
        )
        return True
    except Exception:
        return False

bucket = "healthcare-datalake"

file_key = (
    "raw/claims/2024-01-15/"
    "claims_partner_a.csv"
)

if file_exists(bucket, file_key):
    print("File exists. Start Glue job.")
else:
    print("File missing. Send alert.")

-- Here, head_object() will check the metadata without downloading the file.
-- It will show quick returns and also, it is used in Lambda validation functions.
-- If files are missing, it will also stop the Glue jobs from running.

##•	Explain why the raw layer should have versioning enabled but the curated layer may not need it.

--In Raw Layer, Versioning should be enabled because it stores the original source files.
-- The Raw data is the source data. The partner files shouldn't be lost. 
-- We can recover them, if we overwrite accidentally.
-- This way the previous versions will remain as it is.
-- It will also support auditing and debugging.

--In Curated Layer, Versioning is not necessary. 
-- This will be regenerated by the ETL Jobs. The data can be regenerated from raw files.
-- The storage cost can be reduced with this and only the latest dataset will be required.
